### ISSUE TITLE
StandaloneRenderer RootPath error

### ISSUE THREAD

**Issue by kftw** [tollwerk/TYPO3-ext-tw_base#23]
When creating a `StandaloneRenderer` instance, passing a `$controllerExtensionName` from another extension and then calling, for example,  `StandaloneRenderer->renderParital()`, the following TYPO3 error will occur: 

`(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: filemtime(): stat failed for [SOME_PARTIAL] in [...]vendor/typo3fluid/fluid/src/View/TemplatePaths.php line 625`

This is because inside the constructor of the `StandaloneRenderer` the root paths are getting set like this, relying on the **singular** root path settings.

```
        $this->partialRootPath = rtrim(
            GeneralUtility::getFileAbsFileName($this->configuration['view']['partialRootPath']),
            '/'
        );
```

But in newer extensions, the following settings inside the *setup.txt* do not exist anymore:

* plugin.tx_yourplugin.view.templateRootPath
* plugin.tx_yourplugin.view.partialRootPath
* plugin.tx_yourplugin.view.layoutRootPath

So the `StandaloneRenderer` should traverse through the according **plural** templateRootPath**s**, partialRootPath**s** and layoutRootPath**s** instead.

**Comment by jkphl** [comment]
@kftw Interestingly, the `partialRootPaths` (plural) [are already in use](https://github.com/tollwerk/TYPO3-ext-tw_base/blob/master/Classes/Utility/StandaloneRenderer.php#L199). However, they're ignored for finding the entry template ... Will fix it asap.
