### ISSUE TITLE
Tollwerk\TwBase\ViewHelpers\Icon\UseViewHelper error

### ISSUE THREAD

**Issue by kftw** [tollwerk/TYPO3-ext-tw_base#24]
When using `<base:icon.use icon="Close" />`, the following error occurs:

```
Uncaught TYPO3 Exception: Return value of Tollwerk\TwBase\Utility\SvgIconManager::useIcon() must be an instance of DOMDocument, string returned | TypeError thrown in file [...]/typo3conf/ext/tw_base/Classes/Utility/SvgIconManager.php in line 90. 
```

The reason for this is, that the `getIconDom` function calls the `getUseSource()` function, whose signature defines the return type as String, but the function actually returns a `DOMObject`. 

If the return type in the function signature is changed to `DOMDocument`, there is no error anymore and the following code will be rendered inside the fluid template:

```
<svg viewBox="0 0 100 100.00628" class="Icon Icon--inline Icon--theme-default" aria-hidden="true" role="presentation"><use xlink:href="#close90ec9b8a"></use></svg>
```

But there is no source svg included inside the HTML document.

**Comment by jkphl** [comment]
Solved. It was basically a caching issue (no idea why TYPO3 behaviour might have changed): The component rendering for Fractal was set up as a `USER_INT` object, so it got rendered **after** the `SvgIconManager` tried to inject the sprite (but it had no icon registered at that point, so there was no sprite to inject). Switched to `USER`!
